name: postgres
description: PostgreSQL database driver. Supports statement reuse and binary protocol.
version: 2.2.0
homepage: https://github.com/stablekernel/postgresql-dart

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  buffer: ^1.1.0-nullsafety.0
  crypto: ^3.0.0

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.3
  coverage: any
